version: "3.6"

networks:
  imaging-network:
    name: imaging-network
    external: true

services:
  imaging:
    image: edvinaz/imaging:latest
    container_name: imaging
    build:
      context: ./
      dockerfile: .docker/imaging/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./shared:/var/shared
    environment:
      BASEDIR: /var/www/html
      COMPOSER_AUTH: '${COMPOSER_AUTH}'
      HOME: /var/www/html

    depends_on:
      - imaging_db
    # user: ${CURRENT_UID}
    networks:
      - imaging-network

  imaging_db:
    container_name: imaging_db
    image: mariadb:latest
    volumes:
      - ./.docker/db/storage/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=imaging
      - MYSQL_USER=imaging
      - MYSQL_PASSWORD=imaging
      - MYSQL_DATABASE=imaging
      - TERM=dumb
    ports:
      - "23306:3306"
    networks:
      - imaging-network

  imaging_web:
    image: edvinaz/imaging_web:latest
    container_name: imaging_web
    build:
      context: ./
      dockerfile: .docker/web/Dockerfile
    links:
      - imaging:php_fpm
    ports:
      - "8005:80"
    environment:
      - BASEDIR=/var/www/html

    volumes:
      - ./.docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

    networks:
      - imaging-network

    depends_on:
      - imaging
